doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            ulid: App\SharedKernel\Adapters\Doctrine\DBAL\Types\UlidType
            basket_id: App\BasketContext\Adapters\Doctrine\DBAL\Types\BasketIdType

        mapping_types:
            enum: string
            bit: boolean

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            BasketContext:
                is_bundle: false
                dir: '%kernel.project_dir%/src/BasketContext/Domain/Entity'
                prefix: 'App\BasketContext\Domain\Entity'
                alias: BasketContext

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
